export const adminSections = [
  { key: 'crm', href: '/admin/crm', icon: 'funnel-outline', title: 'Oportunidades comerciais', description: 'Acompanhe interessados, propostas e negociações.' },
  { key: 'commercial-documents', href: '/admin/commercial-documents', icon: 'calculator-outline', title: 'Orçamentos e contratos', description: 'Gerar proposta e contrato para interessados, sem cadastro prévio de cliente.' },
  { key: 'clients', href: '/admin/clients', icon: 'people-outline', title: 'Clientes e acessos', description: 'Convidar, arquivar, reativar, revogar ou excluir com confirmação.' },
  { key: 'projects', href: '/admin/projects', icon: 'briefcase-outline', title: 'Contratos e projetos', description: 'Cadastro inseparável pelo número do contrato e acompanhamento.' },
  { key: 'contract-documents', href: '/admin/contract-documents', icon: 'document-text-outline', title: 'Documentos gerados e aceites', description: 'Baixe documentos preparados e acompanhe o aceite do cliente.' },
  { key: 'document-preparation', href: '/admin/document-preparation', icon: 'document-text-outline', title: 'Preparar documento do projeto', description: 'Preencha e revise termos e anexos antes de gerar o arquivo.' },
  { key: 'document-governance', href: '/admin/document-governance', icon: 'shield-checkmark-outline', title: 'Versões e pendências dos documentos', description: 'Confira versões vigentes, aceites, validade e pendências.' },
  { key: 'document-archive', href: '/admin/document-archive', icon: 'archive-outline', title: 'Arquivos antigos e restauração', description: 'Consulte arquivos guardados e restaure quando necessário.' },
  { key: 'documents', href: { pathname: '/admin/content', params: { tipo: 'document' } }, icon: 'documents-outline', title: 'Documentos', description: 'ART/RRT, contratos, orçamentos e arquivos técnicos classificados por proteção.' },
  { key: 'photos', href: { pathname: '/admin/content', params: { tipo: 'photo' } }, icon: 'images-outline', title: 'Fotos e evolução da obra', description: 'Registros fotográficos protegidos e vinculados aos projetos.' },
  { key: 'tasks', href: '/admin/tasks', icon: 'checkbox-outline', title: 'Tarefas do projeto', description: 'Organize atividades, prazos, dependências e modelos.' },
  { key: 'work-diary', href: '/admin/work-diary', icon: 'book-outline', title: 'Diário de obra', description: 'Registros estruturados, ditado revisável, visibilidade do cliente e relatório PDF.' },
  { key: 'procurement', href: '/admin/procurement', icon: 'cart-outline', title: 'Fornecedores e cotações', description: 'Compare propostas por valor, prazo e condição e registre a escolha.' },
  { key: 'library', href: { pathname: '/admin/content', params: { tipo: 'library' } }, icon: 'library-outline', title: 'Biblioteca', description: 'Guias, catálogos e materiais exclusivos organizados por projeto.' },
  { key: 'financial', href: '/admin/financial', icon: 'receipt-outline', title: 'Financeiro', description: 'Receitas, despesas, valores contratados e histórico.' },
  { key: 'portal-control', href: '/admin/portal-control', icon: 'eye-outline', title: 'Módulos do portal do cliente', description: 'Escolha quais áreas ficam disponíveis em cada projeto.' },
  { key: 'agenda', href: '/admin/agenda', icon: 'calendar-outline', title: 'Agenda', description: 'Compromissos vinculados aos projetos.' },
  { key: 'schedule', href: '/admin/schedule', icon: 'git-branch-outline', title: 'Cronogramas', description: 'Acompanhamento simples por etapas, ordem, status e progresso.' },
  { key: 'construction-schedule', href: '/admin/construction-schedule', icon: 'bar-chart-outline', title: 'Cronograma de obra completo', description: 'Planejamento físico-financeiro, pesos, dependências, Gantt, Curva S e Excel.' },
  { key: 'approvals', href: '/admin/approvals', icon: 'checkmark-done-outline', title: 'Aprovações', description: 'Criar decisões para resposta dos clientes.' },
  { key: 'requests', href: '/admin/requests', icon: 'chatbubbles-outline', title: 'Solicitações', description: 'Atender, responder e atualizar o andamento.' },
  { key: 'notifications', href: '/admin/notifications', icon: 'notifications-outline', title: 'Notificações internas', description: 'Avisos direcionados por cliente, contrato e projeto.' },
  { key: 'security', href: '/admin/security', icon: 'shield-checkmark-outline', title: 'Armazenamento e auditoria', description: 'Uso de espaço, arquivos pendentes e histórico de ações.' },
  { key: 'system-health', href: '/admin/system-health', icon: 'pulse-outline', title: 'Verificar funcionamento', description: 'Confira a disponibilidade dos serviços e pendências técnicas.' },
] as const;
