(function(){'use strict';
const $=id=>document.getElementById(id);let selected='orcamento';
const auxiliary=new Set(['anexo_i','estudo_preliminar','levantamento_tecnico','servico_adicional','autorizacao_imagem','quitacao_encerramento']);
const show=(id,on)=>{const el=$(id);if(el)el.classList.toggle('doc-hidden',!on)};
function filterCommercial(){const box=$('commercialList');if(!box)return;box.querySelectorAll('button[data-action]').forEach(button=>{const action=button.dataset.action||'';let visible=true;if(selected==='orcamento')visible=action==='quote'||action==='quote-archive';else if(selected==='contrato')visible=action==='contract'||action==='contract-archive'||action==='convert';button.classList.toggle('doc-hidden',!visible)});}
function filterGenerator(){const box=$('contractGenerators');if(!box)return;box.querySelectorAll('[data-generator-kind]').forEach(row=>row.classList.toggle('doc-hidden',row.dataset.generatorKind!==selected));}
function activate(kind,{scroll=true}={}){selected=kind;document.querySelectorAll('[data-doc-tab]').forEach(button=>{const active=button.dataset.docTab===kind;button.classList.toggle('ativo',active);button.setAttribute('aria-pressed',active?'true':'false')});
show('panelCommercialCreate',kind==='orcamento');show('panelCommercialExisting',kind==='orcamento'||kind==='contrato');show('panelContractProject',auxiliary.has(kind)||kind==='termo_aceite'||kind==='notificacao_formal');show('panelScope',kind==='anexo_i');show('panelGenerator',auxiliary.has(kind));show('panelApprovals',kind==='termo_aceite');show('panelPrepared',auxiliary.has(kind)||kind==='termo_aceite'||kind==='notificacao_formal');show('panelAttention',kind==='notificacao_formal');
const title=$('selectedDocumentTitle');if(title){const button=document.querySelector(`[data-doc-tab="${kind}"]`);title.textContent=button?.dataset.title||button?.textContent?.trim()||'Documento'}
filterCommercial();filterGenerator();history.replaceState(null,'',`#${kind}`);if(scroll){$('documentWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'})}}
function bind(){document.querySelectorAll('[data-doc-tab]').forEach(button=>button.addEventListener('click',()=>activate(button.dataset.docTab)));const fromHash=(location.hash||'').slice(1);const initial=document.querySelector(`[data-doc-tab="${CSS.escape(fromHash)}"]`)?fromHash:'orcamento';activate(initial,{scroll:false});window.addEventListener('cme:contract-rendered',filterGenerator);const commercial=$('commercialList');if(commercial)new MutationObserver(filterCommercial).observe(commercial,{childList:true,subtree:true});const generators=$('contractGenerators');if(generators)new MutationObserver(filterGenerator).observe(generators,{childList:true,subtree:true});$('toggleArchiveMaintenance')?.addEventListener('click',()=>{const panel=$('archiveMaintenance');if(!panel)return;const opening=panel.classList.contains('doc-hidden');panel.classList.toggle('doc-hidden');$('toggleArchiveMaintenance').setAttribute('aria-expanded',opening?'true':'false')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();