(function(){'use strict';
const $=id=>document.getElementById(id);let selected=null;
const auxiliary=new Set(['anexo_i','estudo_preliminar','levantamento_tecnico','servico_adicional','autorizacao_imagem','quitacao_encerramento']);
const show=(id,on)=>{const el=$(id);if(el)el.classList.toggle('doc-hidden',!on)};
function filterCommercial(){const box=$('commercialList');if(!box)return;box.querySelectorAll('button[data-action]').forEach(button=>{const action=button.dataset.action||'';let visible=true;if(selected==='orcamento')visible=action==='quote'||action==='quote-archive';else if(selected==='contrato')visible=action==='contract'||action==='contract-archive'||action==='convert';button.classList.toggle('doc-hidden',!visible)});}
function filterGenerator(){const box=$('contractGenerators');if(!box)return;box.querySelectorAll('[data-generator-kind]').forEach(row=>row.classList.toggle('doc-hidden',row.dataset.generatorKind!==selected));}
function ensureModal(){const workspace=$('documentWorkspace');if(!workspace||workspace.parentElement?.classList.contains('doc-modal-panel'))return;const backdrop=document.createElement('div');backdrop.id='documentModal';backdrop.className='doc-modal doc-hidden';backdrop.setAttribute('aria-hidden','true');backdrop.innerHTML='<div class="doc-modal-panel" role="dialog" aria-modal="true" aria-labelledby="selectedDocumentTitle"><button type="button" id="closeDocumentModal" class="doc-modal-close" aria-label="Fechar formulário"><i class="fa-solid fa-xmark"></i></button></div>';
document.body.appendChild(backdrop);backdrop.querySelector('.doc-modal-panel').appendChild(workspace);$('closeDocumentModal')?.addEventListener('click',closeModal);backdrop.addEventListener('click',event=>{if(event.target===backdrop)closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!backdrop.classList.contains('doc-hidden'))closeModal()});}
function openModal(){const modal=$('documentModal');if(!modal)return;modal.classList.remove('doc-hidden');modal.setAttribute('aria-hidden','false');document.documentElement.classList.add('doc-modal-open');document.body.classList.add('doc-modal-open');requestAnimationFrame(()=>$('closeDocumentModal')?.focus({preventScroll:true}));}
function closeModal(){const modal=$('documentModal');if(!modal)return;modal.classList.add('doc-hidden');modal.setAttribute('aria-hidden','true');document.documentElement.classList.remove('doc-modal-open');document.body.classList.remove('doc-modal-open');document.querySelector(`[data-doc-tab="${selected}"]`)?.focus({preventScroll:true});}
function activate(kind,{open=true,updateHash=true}={}){selected=kind;document.querySelectorAll('[data-doc-tab]').forEach(button=>{const active=button.dataset.docTab===kind;button.classList.toggle('ativo',active);button.setAttribute('aria-pressed',active?'true':'false')});
show('panelCommercialCreate',kind==='orcamento');show('panelCommercialExisting',kind==='orcamento'||kind==='contrato');show('panelContractProject',auxiliary.has(kind)||kind==='termo_aceite'||kind==='notificacao_formal');show('panelScope',kind==='anexo_i');show('panelGenerator',auxiliary.has(kind));show('panelApprovals',kind==='termo_aceite');show('panelPrepared',auxiliary.has(kind)||kind==='termo_aceite'||kind==='notificacao_formal');show('panelAttention',kind==='notificacao_formal');
const title=$('selectedDocumentTitle');if(title){const button=document.querySelector(`[data-doc-tab="${kind}"]`);title.textContent=button?.dataset.title||button?.textContent?.trim()||'Documento'}
filterCommercial();filterGenerator();if(updateHash)history.replaceState(null,'',`#${kind}`);if(open)openModal();}
function bind(){ensureModal();document.querySelectorAll('[data-doc-tab]').forEach(button=>button.addEventListener('click',()=>activate(button.dataset.docTab)));const fromHash=(location.hash||'').slice(1);if(document.querySelector(`[data-doc-tab="${CSS.escape(fromHash)}"]`))activate(fromHash,{open:true,updateHash:false});window.addEventListener('cme:contract-rendered',filterGenerator);const commercial=$('commercialList');if(commercial)new MutationObserver(filterCommercial).observe(commercial,{childList:true,subtree:true});const generators=$('contractGenerators');if(generators)new MutationObserver(filterGenerator).observe(generators,{childList:true,subtree:true});$('toggleArchiveMaintenance')?.addEventListener('click',()=>{const panel=$('archiveMaintenance');if(!panel)return;const opening=panel.classList.contains('doc-hidden');panel.classList.toggle('doc-hidden');$('toggleArchiveMaintenance').setAttribute('aria-expanded',opening?'true':'false')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();