import { createClient } from 'supabase';
import { generateNativeOptionsDocx } from './native-options-docx.ts';

const corsHeaders={
 'Access-Control-Allow-Origin':Deno.env.get('ALLOWED_ORIGIN')??'*',
 'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
 'Access-Control-Allow-Methods':'POST, OPTIONS',
};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}});
type Obj=Record<string,unknown>;
function env(){const url=Deno.env.get('SUPABASE_URL'),anonKey=Deno.env.get('SUPABASE_ANON_KEY'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anonKey||!serviceKey)throw new Error('Configuração segura ausente.');return {url,anonKey,serviceKey};}
async function requireAdmin(req:Request){const authorization=req.headers.get('Authorization');if(!authorization?.startsWith('Bearer '))throw new Error('Sessão administrativa ausente.');const {url,anonKey,serviceKey}=env();const caller=createClient(url,anonKey,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await caller.auth.getUser();if(userError||!userData.user)throw new Error('Sessão administrativa inválida.');const {data:isAdmin,error:adminError}=await caller.rpc('is_portal_admin');if(adminError||isAdmin!==true)throw new Error('Acesso administrativo necessário.');return {authorization,url,anonKey,service:createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),user:userData.user};}
const selected=(v:unknown,key:string)=>Array.isArray(v)?v.map(String).includes(key):String(v??'')===key;
const list=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):v?[String(v)]:[];
const text=(v:unknown)=>String(v??'').trim();
function validate(kind:string,o:Obj){if(kind==='autorizacao_imagem'){if(!list(o.materials).length)return'Selecione ao menos um material autorizado.';if(!list(o.channels).length)return'Selecione ao menos um canal autorizado.';if(text(o.wait_months)&&(!Number.isFinite(Number(o.wait_months))||Number(o.wait_months)<=0))return'Informe um prazo de espera em meses maior que zero.'}if(kind==='termo_aceite'){if(!text(o.acceptance))return'Selecione a forma de aceite.';if(selected(o.acceptance,'accepted_with_notes')&&!text(o.acceptance_notes))return'Descreva as ressalvas antes de gerar o documento.'}if(kind==='servico_adicional'){if(!list(o.reasons).length)return'Selecione a origem da solicitação adicional.';if(selected(o.reasons,'other')&&!text(o.other_reason))return'Descreva o motivo em “Outro”.';if(!text(o.pricing))return'Selecione um único critério comercial.';if(!text(o.additional_service_description))return'Descreva o serviço adicional.'}if(kind==='quitacao_encerramento'){if(!text(o.closing_reason))return'Selecione um único motivo do encerramento.';if(selected(o.closing_reason,'other')&&!text(o.closing_other))return'Descreva o outro motivo do encerramento.';if(!text(o.financial))return'Selecione a situação financeira.';if(selected(o.financial,'balance')&&(!text(o.balance_value)||!text(o.balance_due)))return'Para saldo pendente, informe valor e vencimento.'}return''}
async function proxyCore(url:string,anonKey:string,authorization:string,body:unknown){const response=await fetch(`${url}/functions/v1/generate-contract-document`,{method:'POST',headers:{Authorization:authorization,apikey:anonKey,'Content-Type':'application/json'},body:JSON.stringify(body)});let data:Obj={};try{data=await response.json()}catch{data={error:'Resposta inválida do gerador principal.'}}return {response,data}}
const nativeKinds=new Set(['termo_aceite','servico_adicional','autorizacao_imagem','quitacao_encerramento','levantamento_tecnico']);

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Método não permitido.'},405);try{const {authorization,url,anonKey,service,user}=await requireAdmin(req);const body=await req.json() as Obj;const documentId=text(body.documentId);if(!/^[0-9a-f-]{36}$/i.test(documentId))return json({error:'Documento inválido.'},400);const rowBefore=await service.from('documentos').select('id,document_kind,generated_data').eq('id',documentId).maybeSingle();if(rowBefore.error)throw rowBefore.error;if(!rowBefore.data)return json({error:'Documento não encontrado.'},404);if(body.action!=='send'){const frozen=await service.from('document_emission_snapshots').select('id').eq('document_id',documentId).maybeSingle();if(frozen.error)throw frozen.error;if(frozen.data)return json({error:'Esta versão já foi emitida e está congelada. Prepare uma nova versão para gerar outro Word.'},409)}const source=(rowBefore.data.generated_data&&typeof rowBefore.data.generated_data==='object'?rowBefore.data.generated_data:{}) as Obj;const options=(source.document_options&&typeof source.document_options==='object'?source.document_options:{}) as Obj;if(body.action!=='send'){const issue=validate(String(rowBefore.data.document_kind||''),options);if(issue)return json({error:issue},422)}const core=await proxyCore(url,anonKey,authorization,body);if(!core.response.ok)return json(core.data,core.response.status);if(body.action==='send')return json(core.data,core.response.status);
const row=await service.from('documentos').select('id,arquivo,storage_bucket,document_kind,generated_data,versao').eq('id',documentId).single();if(row.error)throw row.error;if(!row.data.arquivo)throw new Error('O gerador principal não produziu o arquivo Word.');const generatedData=(row.data.generated_data&&typeof row.data.generated_data==='object'?row.data.generated_data:{}) as Obj;let nativeRendered=false;
if(nativeKinds.has(String(row.data.document_kind||''))&&Object.keys(options).length>0){const signature=await service.rpc('service_get_professional_signature');if(signature.error)throw signature.error;const bytes=await generateNativeOptionsDocx(String(row.data.document_kind||''),{...generatedData,document_options:options},(signature.data&&typeof signature.data==='object'?signature.data:{}) as Record<string,string|undefined>);if(bytes){const bucket=row.data.storage_bucket||'documentos';const upload=await service.storage.from(bucket).upload(row.data.arquivo,bytes,{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',upsert:true});if(upload.error)throw upload.error;nativeRendered=true;}}
const updatedData={...generatedData,document_options:options,document_options_applied_at:new Date().toISOString(),document_options_rendering:nativeRendered?'native_docx':'core'};const updated=await service.from('documentos').update({generated_data:updatedData}).eq('id',documentId);if(updated.error)throw updated.error;await service.from('audit_log').insert({user_id:user.id,action:'finalize_contract_document_options',entity_type:'documentos',entity_id:documentId,details:{document_kind:row.data.document_kind,version:row.data.versao,options_applied:Object.keys(options).length>0,rendering:nativeRendered?'native_docx':'core'}});return json({...core.data,version:row.data.versao,optionsApplied:Object.keys(options).length>0,optionsRendering:nativeRendered?'native_docx':'core',snapshotFrozen:true},200)}catch(error){const message=error instanceof Error?error.message:'Não foi possível finalizar o documento.';return json({error:message},message.includes('Acesso')?403:message.includes('Sessão')?401:500)}});
