import { createClient } from 'supabase';
import { encodeBase64 } from 'jsr:@std/encoding@1/base64';
import JSZip from 'npm:jszip@3.10.1';

const corsHeaders={'Access-Control-Allow-Origin':Deno.env.get('ALLOWED_ORIGIN')??'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}});
async function requireAdmin(req:Request){const authorization=req.headers.get('Authorization');if(!authorization?.startsWith('Bearer '))throw new Error('Sessão administrativa ausente.');const url=Deno.env.get('SUPABASE_URL'),anonKey=Deno.env.get('SUPABASE_ANON_KEY'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anonKey||!serviceKey)throw new Error('Configuração segura ausente.');const caller=createClient(url,anonKey,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await caller.auth.getUser();if(userError||!userData.user)throw new Error('Sessão administrativa inválida.');const {data:isAdmin,error:adminError}=await caller.rpc('is_portal_admin');if(adminError||isAdmin!==true)throw new Error('Acesso administrativo necessário.');return {caller,service:createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),user:userData.user};}
const safeFileName=(value:string)=>value.replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim().slice(0,160)||'documento.docx';
const arr=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const xmlEsc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function mark(xml:string,label:string,on:boolean){return on?xml.replaceAll(`☐ ${label}`,`☒ ${label}`):xml;}
function replaceLine(xml:string,prefix:string,value:unknown){const v=String(value??'').trim();if(!v)return xml;const start=xml.indexOf(prefix);if(start<0)return xml;const textEnd=xml.indexOf('</w:t>',start);if(textEnd<0)return xml;const contentStart=start+prefix.length;return xml.slice(0,contentStart)+xmlEsc(v)+xml.slice(textEnd);}
async function personalize(bytes:Uint8Array,kind:string,data:Record<string,unknown>){const opts=(data.document_options&&typeof data.document_options==='object'?data.document_options:data) as Record<string,unknown>;if(!opts||!Object.keys(opts).length)return bytes;const zip=await JSZip.loadAsync(bytes);const file=zip.file('word/document.xml');if(!file)return bytes;let xml=await file.async('string');
 if(kind==='autorizacao_imagem'){
  const materials=arr(opts.materials),channels=arr(opts.channels),privacy=arr(opts.privacy);
  [['facade','Fotografias externas / fachada.'],['interiors','Fotografias de interiores.'],['renders','Renders 3D e imagens de apresentação.'],['plans','Plantas e pranchas sem dados pessoais sensíveis.'],['videos','Vídeos e tour virtual 360°.'],['work_records','Registros de obra sem identificação de pessoas.']].forEach(([k,l])=>xml=mark(xml,l,materials.includes(k)));
  [['portfolio','Portfólio profissional e site.'],['social','Redes sociais.'],['commercial','Apresentações comerciais.'],['technical','Publicações técnicas, concursos e premiações.'],['print','Material impresso institucional.']].forEach(([k,l])=>xml=mark(xml,l,channels.includes(k)));
  [['hide_address','Não divulgar endereço exato.'],['hide_client','Não divulgar nome do(a) cliente.'],['no_people','Não utilizar imagens com pessoas identificáveis sem autorização específica.']].forEach(([k,l])=>xml=mark(xml,l,privacy.includes(k)));
  const months=String(opts.wait_months??'').trim();if(months)xml=xml.replace('☐ Aguardar ______ meses após a conclusão para a primeira divulgação.',`☒ Aguardar ${xmlEsc(months)} meses após a conclusão para a primeira divulgação.`);
  const other=String(opts.other_restrictions??'').trim();if(other)xml=xml.replace('☐ Outras restrições: _______________________________________________',`☒ Outras restrições: ${xmlEsc(other)}`);
 }
 if(kind==='termo_aceite'){
  const acceptance=arr(opts.acceptance);xml=mark(xml,'Aceito sem ressalvas.',acceptance.includes('accepted'));xml=mark(xml,'Aceito com ressalvas descritas abaixo:',acceptance.includes('accepted_with_notes'));const notes=String(opts.acceptance_notes??'').trim();if(notes)xml=xml.replace('_______________________________________________________________________________',xmlEsc(notes));
 }
 if(kind==='servico_adicional'){
  const reasons=arr(opts.reasons),pricing=arr(opts.pricing),approval=arr(opts.approval);
  [['extra_revisions','Revisão além das rodadas incluídas.'],['scope_change','Alteração de escopo, premissas, programa, metragem ou layout já aprovado.'],['level_upgrade','Migração para nível de prestação superior ao contratado.'],['survey','Vistoria ou levantamento não incluído no escopo original.'],['editable_file','Arquivo editável ou formato não previsto.']].forEach(([k,l])=>xml=mark(xml,l,reasons.includes(k)));
  if(reasons.includes('other'))xml=xml.replace('☐ Outro: _______________________________________________',`☒ Outro: ${xmlEsc(opts.other_reason||'')}`);
  [['hour','hora técnica'],['percentage','percentual sobre etapa afetada'],['fixed','valor fechado aprovado por orçamento específico.']].forEach(([k,l])=>{if(pricing.includes(k))xml=xml.replace(`☐ ${l}`,`☒ ${l}`)});
  xml=mark(xml,'Aprovo a alteração acima e autorizo o início do serviço adicional nos limites deste termo.',approval.includes('approved'));
  if(String(opts.additional_service_description??'').trim())xml=xml.replace('Descrever somente a nova solicitação; o escopo original já está registrado acima.',xmlEsc(opts.additional_service_description));
  if(String(opts.additional_value??'').trim())xml=xml.replace('Valor adicional aprovado: _______________________________________________',`Valor adicional aprovado: ${xmlEsc(opts.additional_value)}`);
  if(String(opts.schedule_impact??'').trim())xml=xml.replace('Impacto adicional no cronograma: _________________________________________',`Impacto adicional no cronograma: ${xmlEsc(opts.schedule_impact)}`);
 }
 if(kind==='quitacao_encerramento'){
  const reason=arr(opts.closing_reason),financial=arr(opts.financial);
  [['completed','Conclusão integral do escopo contratado.'],['client_termination','Rescisão antecipada por iniciativa do(a) CONTRATANTE.'],['contractor_termination','Rescisão antecipada por iniciativa do(a) CONTRATADO(A).'],['mutual','Rescisão por mútuo acordo.']].forEach(([k,l])=>xml=mark(xml,l,reason.includes(k)));
  if(reason.includes('other'))xml=xml.replace('☐ Outro: _______________________________________________',`☒ Outro: ${xmlEsc(opts.closing_other||'')}`);
  xml=mark(xml,'Quitação integral.',financial.includes('paid'));
  if(financial.includes('balance'))xml=xml.replace('☐ Existe saldo pendente no valor de __________________ com vencimento em __________.',`☒ Existe saldo pendente no valor de ${xmlEsc(opts.balance_value||'__________________')} com vencimento em ${xmlEsc(opts.balance_due||'__________')}.`);
  if(String(opts.delivered_files??'').trim())xml=xml.replace('Arquivos e documentos finais entregues: __________________________________________',`Arquivos e documentos finais entregues: ${xmlEsc(opts.delivered_files)}`);
  if(String(opts.open_items??'').trim())xml=xml.replace('Pendências técnicas ou administrativas que permanecem abertas: _____________________',`Pendências técnicas ou administrativas que permanecem abertas: ${xmlEsc(opts.open_items)}`);
  if(String(opts.public_processes??'').trim())xml=xml.replace('Processos perante órgãos públicos ainda em andamento, quando aplicável: _____________',`Processos perante órgãos públicos ainda em andamento, quando aplicável: ${xmlEsc(opts.public_processes)}`);
 }
 if(kind==='levantamento_tecnico'){
  const observed=arr(opts.observed),conditions=arr(opts.conditions);
  [['electrical','Pontos elétricos'],['hydraulic','Pontos hidráulicos'],['structure','Estrutura aparente'],['frames','Esquadrias'],['finishes','Revestimentos'],['roof','Cobertura'],['drainage','Drenagem'],['access','Acessos'],['other','Outros']].forEach(([k,l])=>xml=mark(xml,l,observed.includes(k)));
  [['cracks','Fissuras/trincas'],['moisture','Umidade/infiltração'],['levels','Desníveis'],['corrosion','Corrosão aparente'],['document_mismatch','Divergência entre realidade e documentos fornecidos'],['restricted_access','Acesso restrito a algum elemento']].forEach(([k,l])=>xml=mark(xml,l,conditions.includes(k)));
  if(String(opts.inspection_datetime??'').trim())xml=xml.replace('Data e horário da vistoria: _______________________________________________',`Data e horário da vistoria: ${xmlEsc(opts.inspection_datetime)}`);
  if(String(opts.site_contact??'').trim())xml=xml.replace('Responsável pelo acompanhamento no local: __________________________________',`Responsável pelo acompanhamento no local: ${xmlEsc(opts.site_contact)}`);
  if(String(opts.conditions_description??'').trim())xml=xml.replace('Descrição: _____________________________________________________________________',`Descrição: ${xmlEsc(opts.conditions_description)}`);
 }
 zip.file('word/document.xml',xml);return await zip.generateAsync({type:'uint8array',compression:'DEFLATE'});
}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Método não permitido.'},405);try{const {caller,service,user}=await requireAdmin(req);const body=await req.json() as {documentId?:string;archive?:boolean;expectedDocumentKind?:string};const documentId=typeof body.documentId==='string'?body.documentId:'';const archive=body.archive===true;const expectedDocumentKind=typeof body.expectedDocumentKind==='string'?body.expectedDocumentKind:'';if(!/^[0-9a-f-]{36}$/i.test(documentId))return json({error:'Documento inválido.'},400);const {error:rateError}=await caller.rpc('consume_admin_rate_limit',{p_action:archive?'document-delivery-archive':'document-delivery-download'});if(rateError)return json({error:'Muitas operações em sequência. Aguarde e tente novamente.'},429);
 const rowResult=await service.from('documentos').select('id,nome,arquivo,storage_bucket,categoria,document_kind,workflow_status,versao,cliente_id,projeto_id,contract_id,generated_data').eq('id',documentId).maybeSingle();if(rowResult.error)throw rowResult.error;if(!rowResult.data)return json({error:'Documento não encontrado.'},404);const row=rowResult.data;const generatedData=row.generated_data&&typeof row.generated_data==='object'?row.generated_data as Record<string,unknown>:{};const actualDocumentKind=typeof row.document_kind==='string'&&row.document_kind?row.document_kind:typeof generatedData.commercial_document_kind==='string'?generatedData.commercial_document_kind:'';if(!expectedDocumentKind)return json({error:'Informe o tipo de documento esperado para o download.'},400);if(!actualDocumentKind||actualDocumentKind!==expectedDocumentKind)return json({error:'O arquivo preparado não corresponde ao tipo solicitado. Atualize a tela e gere novamente.'},409);if(!row.arquivo)return json({error:'O Word ainda não foi gerado para entrega.'},409);
 const bucket=row.storage_bucket||'documentos';const downloaded=await service.storage.from(bucket).download(row.arquivo);if(downloaded.error||!downloaded.data)throw downloaded.error??new Error('Não foi possível obter o Word gerado.');let bytes=new Uint8Array(await downloaded.data.arrayBuffer());bytes=await personalize(bytes,actualDocumentKind,generatedData);if(bytes.byteLength>20*1024*1024)return json({error:'O Word gerado ultrapassa o limite de 20 MB para entrega direta.'},413);
 let partyName=typeof generatedData.prospect_name==='string'?generatedData.prospect_name:typeof generatedData.client_name==='string'?generatedData.client_name:null;if(!partyName&&row.cliente_id){const c=await service.from('clientes').select('nome').eq('id',row.cliente_id).maybeSingle();if(!c.error&&c.data?.nome)partyName=c.data.nome}const commercialRecordId=typeof generatedData.commercial_record_id==='string'&&/^[0-9a-f-]{36}$/i.test(generatedData.commercial_record_id)?generatedData.commercial_record_id:null;const documentNumber=typeof generatedData.contract_number==='string'&&generatedData.contract_number?generatedData.contract_number:typeof generatedData.quote_number==='string'?generatedData.quote_number:null;const fileName=safeFileName(`${row.nome}.docx`);const now=new Date().toISOString();
 const historyInsert=await service.from('document_generation_history').insert({document_id:row.id,document_kind:row.document_kind??row.categoria,document_name:row.nome,document_number:documentNumber,version:row.versao,workflow_status:row.workflow_status,client_id:row.cliente_id,project_id:row.projeto_id,contract_id:row.contract_id,commercial_record_id:commercialRecordId,party_name:partyName,storage_mode:archive?'archived':'download_only',file_size_bytes:bytes.byteLength,generated_by:user.id,generated_at:now}).select('id').single();if(historyInsert.error)throw historyInsert.error;const historyId=historyInsert.data.id as string;let archivePath:string|null=null;
 if(archive){const originalName=row.arquivo.split('/').pop()||fileName;archivePath=`_generated_archive/${row.id}/${historyId}-${safeFileName(originalName)}`;const uploaded=await service.storage.from(bucket).upload(archivePath,bytes,{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',upsert:false});if(uploaded.error)throw uploaded.error;if(archivePath!==row.arquivo){const removed=await service.storage.from(bucket).remove([row.arquivo]);if(removed.error)throw removed.error}const updated=await service.from('documentos').update({arquivo:archivePath,storage_bucket:bucket,archived_explicitly:true,last_downloaded_at:now,archived_storage_size:bytes.byteLength,purged_at:null}).eq('id',row.id);if(updated.error)throw updated.error;const hu=await service.from('document_generation_history').update({archive_path:archivePath}).eq('id',historyId);if(hu.error)throw hu.error}else{const removed=await service.storage.from(bucket).remove([row.arquivo]);if(removed.error)throw removed.error;const updated=await service.from('documentos').update({arquivo:null,archived_explicitly:false,last_downloaded_at:now,archived_storage_size:null}).eq('id',row.id);if(updated.error)throw updated.error}
 await service.from('audit_log').insert({user_id:user.id,action:archive?'download_and_archive_generated_document':'download_generated_document_without_archive',entity_type:'documentos',entity_id:row.id,details:{history_id:historyId,file_size_bytes:bytes.byteLength,archive_path:archivePath,document_options_applied:Boolean(generatedData.document_options)}});return json({delivered:true,documentId:row.id,documentKind:actualDocumentKind,historyId,fileName,contentBase64:encodeBase64(bytes),archived:archive,archivePath,fileSizeBytes:bytes.byteLength});}catch(error){const message=error instanceof Error?error.message:'Não foi possível entregar o Word gerado.';return json({error:message},message.includes('Acesso')?403:message.includes('Sessão')?401:500)}});